apiVersion: v1
kind: Service
metadata:
  name: demo-todo-app-frontend
  namespace: demo-project
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: demo-todo-app 
    tier: demo-todo-app-frontend
  type: LoadBalancer

