apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-app-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
        tier: todo-app-frontend
        track: stable
    spec:
      containers:
        - name: todo-app-frontend
          image: "jeffleevm/todo-app-frontend:latest"
          ports:
          - containerPort: 80
